<a href="https://colab.research.google.com/github/Vrinda-2004/Assessmenttest/blob/main/PandasCASESTUDY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/IMDB-Movie-Data.csv')
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [3]:
data.shape

(1000, 12)

In [4]:
data.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [5]:
data.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [6]:
data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [7]:
data.isna().sum() # to find missing values

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [8]:
data.duplicated().sum() # to check duplicates

np.int64(0)

In [10]:
data.drop_duplicates() # to remove duplicates

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [17]:
data.rename(columns={'Title':'Movie_Title'}, inplace=True) # inplace is used to update original dataFrame
data.columns

Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [18]:
data['Genre'].unique() # to get unique genres. unique() is used to remove duplicates and also returns values present in a column

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [33]:
data['Genre_Count'] = data['Genre'].str.split(',').str.len()  # instead of str.len() we can also use apply(len)
data[['Movie_Title', 'Genre', 'Genre_Count']]

                 Movie_Title                     Genre  Genre_Count
0    Guardians of the Galaxy   Action,Adventure,Sci-Fi            3
1                 Prometheus  Adventure,Mystery,Sci-Fi            3
2                      Split           Horror,Thriller            2
3                       Sing   Animation,Comedy,Family            3
4              Suicide Squad  Action,Adventure,Fantasy            3
..                       ...                       ...          ...
995     Secret in Their Eyes       Crime,Drama,Mystery            3
996          Hostel: Part II                    Horror            1
997   Step Up 2: The Streets       Drama,Music,Romance            3
998             Search Party          Adventure,Comedy            2
999               Nine Lives     Comedy,Family,Fantasy            3

[1000 rows x 3 columns]

In [43]:
data['Revenue (Millions)'] = data['Revenue (Millions)'].fillna(
    data['Revenue (Millions)'].mean()
    ) # fillna/ Imputation - Replaces missing values with average.
data['Revenue (Millions)']

0      333.130000
1      126.460000
2      138.120000
3      270.320000
4      325.020000
          ...
995     82.956376
996     17.540000
997     58.010000
998     82.956376
999     19.640000
Name: Revenue (Millions), Length: 1000, dtype: float64

In [42]:
data['Metascore'] = data['Metascore'].fillna(
    data['Metascore'].mean()
)
data['Metascore']

0      76.0
1      65.0
2      62.0
3      59.0
4      40.0
       ...
995    45.0
996    46.0
997    50.0
998    22.0
999    11.0
Name: Metascore, Length: 1000, dtype: float64

In [68]:
# data.nlargest(5,'Rating')[['Movie_Title','Rating']]
data.sort_values(by='Rating', ascending=False)[['Movie_Title', 'Rating']].head()

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

In [53]:
data.loc[data['Revenue (Millions)'].idxmax()]

Rank                                                                 51
Movie_Title                  Star Wars: Episode VII - The Force Awakens
Genre                                          Action,Adventure,Fantasy
Description           Three decades after the defeat of the Galactic...
Director                                                    J.J. Abrams
Actors                Daisy Ridley, John Boyega, Oscar Isaac, Domhna...
Year                                                               2015
Runtime (Minutes)                                                   136
Rating                                                              8.1
Votes                                                            661608
Revenue (Millions)                                               936.63
Metascore                                                          81.0
Genre_Count                                                           3
Name: 50, dtype: object

In [72]:
data.loc[data['Revenue (Millions)'].idxmin()]

Rank                                                                232
Movie_Title                                            A Kind of Murder
Genre                                              Crime,Drama,Thriller
Description           In 1960s New York, Walter Stackhouse is a succ...
Director                                                   Andy Goddard
Actors                Patrick Wilson, Jessica Biel, Haley Bennett, V...
Year                                                               2016
Runtime (Minutes)                                                    95
Rating                                                              5.2
Votes                                                              3305
Revenue (Millions)                                                  0.0
Metascore                                                          50.0
Genre_Count                                                           3
Name: 231, dtype: object

In [73]:
data.sort_values(by='Revenue (Millions)')[['Movie_Title', 'Revenue (Millions)']]

                                    Movie_Title  Revenue (Millions)
231                            A Kind of Murder                0.00
27                                   Dead Awake                0.01
68                                    Wakefield                0.01
961                             Into the Forest                0.01
321                                    Lovesong                0.01
..                                          ...                 ...
54                              The Dark Knight              533.32
76                                 The Avengers              623.28
85                               Jurassic World              652.18
87                                       Avatar              760.51
50   Star Wars: Episode VII - The Force Awakens              936.63

[1000 rows x 2 columns]

In [74]:
data.groupby('Director')['Rating'].mean()

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

In [97]:
data['Year'].value_counts()

Year
2016    297
2015    127
2014     98
2013     91
2012     64
2011     63
2010     60
2007     53
2008     52
2009     51
2006     44
Name: count, dtype: int64

In [101]:
# data[(data['Rating'] > 8) &
#    (data['Revenue (Millions)'] > 100)]
data[(data['Rating'] > 8) & (data['Revenue (Millions)'] > 100)][['Movie_Title', 'Rating']]

     Movie_Title  Rating
0            NaN     8.1
6            NaN     8.3
36           NaN     8.6
50           NaN     8.1
54           NaN     9.0
67           NaN     8.1
74           NaN     8.1
76           NaN     8.1
77           NaN     8.3
80           NaN     8.8
82           NaN     8.2
83           NaN     8.1
92           NaN     8.1
99           NaN     8.5
114          NaN     8.1
124          NaN     8.5
138          NaN     8.1
144          NaN     8.4
241          NaN     8.2
427          NaN     8.1
499          NaN     8.3
634          NaN     8.4
645          NaN     8.2
688          NaN     8.3
772          NaN     8.1

In [102]:
data.groupby('Director').agg({
    'Rating':'mean',
    'Revenue (Millions)':'mean'
})

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

In [103]:
data.groupby('Year').agg({
    'Movie_Title':'count',
    'Rating':'mean'
})

      Movie_Title    Rating
Year
2006            0  7.125000
2007            0  7.133962
2008            0  6.784615
2009            0  6.960784
2010            0  6.826667
2011            0  6.838095
2012            0  6.925000
2013            0  6.812088
2014            0  6.837755
2015            0  6.602362
2016            0  6.436700

In [106]:
data['Profitability'] = (
    data['Revenue (Millions)']
    /
    data['Runtime (Minutes)']
)
data['Profitability']

0      2.753140
1      1.019839
2      1.180513
3      2.502963
4      2.642439
         ...
995    0.747355
996    0.186596
997    0.591939
998    0.892004
999    0.225747
Name: Profitability, Length: 1000, dtype: float64

In [107]:
data.nlargest(10,'Profitability')[
    ['Movie_Title','Profitability']
]

     Movie_Title  Profitability
50           NaN       6.886985
85           NaN       5.259516
119          NaN       5.013299
87           NaN       4.694506
76           NaN       4.358601
15           NaN       4.233448
688          NaN       4.028932
12           NaN       4.001278
174          NaN       3.928824
797          NaN       3.755612

In [108]:
def category(rating):

    if rating < 6:
        return 'Poor'

    elif rating < 7.5:
        return 'Average'

    else:
        return 'Excellent'

data['Rating_Category'] = data['Rating'].apply(category)
data['Rating_Category'].value_counts()

Rating_Category
Average      586
Excellent    230
Poor         184
Name: count, dtype: int64

In [113]:
def movie_score(row):

    return (
        row['Rating'] * 10
        + row['Revenue (Millions)']
    )

data['Score'] = data.apply(movie_score, axis=1)
data[['Movie_Title','Score']].head()

   Movie_Title   Score
0          NaN  414.13
1          NaN  196.46
2          NaN  211.12
3          NaN  342.32
4          NaN  387.02